name: Create Vercel Project

on: push

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: git fetch origin main
      - run: npm install
      - run: node scripts/create-project.mjs ${{ github.sha }}
